id = "pathy"
name = "Pathy"
version = "0.2.0"
schema_version = 1
description = "Sidecar LSP server for filesystem path completions inside string literals."
authors = ["Avimitin"]
repository = "https://github.com/Avimitin/pathy"
capabilities = [
  { kind = "process:exec", command = "*", args = ["**"] },
  { kind = "download_file", host = "github.com", path = ["**"] }
]

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.pathy]
languages = [
  "Bash",
  "C",
  "C++",
  "C#",
  "Clojure",
  "CSS",
  "Dart",
  "Diff",
  "Docker",
  "Dockerfile",
  "Elixir",
  "Erlang",
  "F#",
  "Go",
  "Gradle",
  "GraphQL",
  "Groovy",
  "Haskell",
  "HCL",
  "HTML",
  "Java",
  "JavaScript",
  "JSON",
  "JSX",
  "Kotlin",
  "Lua",
  "Makefile",
  "Markdown",
  "Maven",
  "Nix",
  "Objective-C",
  "Perl",
  "PHP",
  "Plain Text",
  "Prisma",
  "Protobuf",
  "Python",
  "R",
  "Ruby",
  "Rust",
  "Scala",
  "Shell",
  "SQL",
  "Svelte",
  "Swift",
  "TOML",
  "TSX",
  "Terraform",
  "TypeScript",
  "Typst",
  "Vim",
  "Vue",
  "XML",
  "YAML",
  "Zig",
]
